// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrbptzorqyxplylhqkfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyYnB0em9ycXl4cGx5bGhxa2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Njg0MzMsImV4cCI6MjA2OTM0NDQzM30.A5oOu50ESTPk3InpnC7WacbJvzGMQOXlZNECwODu7j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});